name: pawsafe
description: A humane stray dog management and campus safety application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (WEB SAFE)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.5
  firebase_analytics: ^10.10.7

  # UI
  cupertino_icons: ^1.0.2
  provider: ^6.1.1

  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  google_generative_ai: ^0.4.6

  http: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_cloud_firestore: 2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/background.png  
    - assets/images/campus_map.png
  fonts:
    - family: SourGummy
      fonts:
        - asset: assets/fonts/SourGummy-Regular.ttf
  